title: Sell me something
hero_image: images/banner.png
description: sell-me-something description
version: 4
listed: false
copyedit: false
last_tested: "2022-05-24"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
