title: Sell me something
hero_image: images/banner.png
description: Make a webpage for a product or idea.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - 
    title: Introduction
  - 
    title: What are you selling?
  - 
    title: Add your content
    completion: engaged
  - 
    title: Use animation
  - 
    title: Add more style
    completion: internal
  - 
    title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion: external
  - 
    title: Upgrade your project
  - 
    title: Share
  - 
    title: What next?
